### ISSUE TITLE
Add redis DB and bullMQ

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard-ai-builder#156]
Add the redis docker image to the docker compose. 

PD: We are still unsure if the Docker Compose configuration in this repository will be used to deploy the app to production. However, having it available will make testing easier.

**Comment by maxicapodacqua** [comment]
@RodriSanchez1 as part of this issue I will add bullMQ to the package.json, as well as a simple worker and an example page for you to test this out, so for the next issue #157 you can just focus on the logic for your solution

**Comment by RodriSanchez1** [comment]
Nice! thanks @maxicapodacqua
