### ISSUE TITLE
Create Dashboard page

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard-ai-builder#3]
[See parallel routes](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes)

Folder structure:
```
-App
   /dashboard/
       @history
       @generated-board
       @prompt-form
```
       
![image](https://github.com/cboard-org/cboard-board-builder/assets/80465873/fb0d0d26-81e8-4649-9632-9e2407076b53)

**Comment by tomivm** [comment]
The last design of the UI designer is a bit different.
![grid layout](https://github.com/cboard-org/cboard-ai-builder/assets/21298844/ecf37b82-d65b-433a-9c44-c6490b5db5c0)
