### ISSUE TITLE
Implement a button to open the app in full screen

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard-ai-builder#46]
Like on the Cboard app. create a button to open the app on the entire screen.

[Cboard implementation](https://github.com/cboard-org/cboard/blob/master/src/components/UI/FullScreenButton/FullScreenButton.js):
<img width="423" alt="image" src="https://github.com/cboard-org/cboard-ai-builder/assets/21298844/e1a70bf0-00c7-4ad5-bbc5-ab290fbcdcce">

<img width="1470" alt="image" src="https://github.com/cboard-org/cboard-ai-builder/assets/21298844/207f5a6f-7648-4031-a853-c7a38e54ff88">

**Comment by tomivm** [comment]
Hey @sussysloth ! do you want to take this issue?

**Comment by sussysloth** [comment]
Yes please! thanks!
